//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarxEnFw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masina
    {
        public string Combustibil { get; set; }
        public Nullable<int> Kilometraj { get; set; }
        public Nullable<int> Pret { get; set; }
        public Nullable<int> AnFab { get; set; }
        public Nullable<int> Id_Model { get; set; }
        public int Id_Masina { get; set; }
    
        public virtual ModelMasina ModelMasina { get; set; }
    }
}
