//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarxEnFw
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelMasina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelMasina()
        {
            this.Masinas = new HashSet<Masina>();
        }
    
        public int Id { get; set; }
        public string NumeModel { get; set; }
        public int Id_Marca { get; set; }
    
        public virtual MarcaMasina MarcaMasina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masina> Masinas { get; set; }
    }
}
