//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarxEnFw
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Carx_dbEntities2 : DbContext
    {
        public Carx_dbEntities2()
            : base("name=Carx_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MarcaMasina> MarcaMasinas { get; set; }
        public virtual DbSet<Masina> Masinas { get; set; }
        public virtual DbSet<ModelMasina> ModelMasinas { get; set; }
    }
}
